### ISSUE TITLE
Terminal closes very quickly, despite setting Python to PATH during installation

### ISSUE THREAD

**Issue by Kiy-Ko** [doxy-ai/ZatsuViewer#1]
I still get the issue mentioned in the FAQ despite Python 3.12 being set to PATH during Python installation.

**Comment by doxy-ai** [comment]
Is this still the case in the latest version?

**Comment by AndrioCelos** [comment]
This could be related to #2.

> I still get the issue mentioned in the FAQ despite Python 3.12 being set to PATH during Python installation.

Please follow the manual installation procedure described in [the readme](https://github.com/doxy-ai/ZatsuViewer#quick-start-other-platforms-windows-too-if-youre-feeling-advanced), then provide any exception messages in the terminal when trying to run the app.

If you see the same exception mentioned in that issue, install Flask v2.3.3 by running this command: `pip install flask==2.3.3`
